### ISSUE TITLE
Play non-youtube videos

### ISSUE THREAD

**Issue by 80svault** [grt107/grt-youtube-popup#1]
Great simple script for playing YouTube videos. I want to use this script on my website, but am not using YouTube videos. I have my own hosted videos with JWPlayer. If I create a page with a hosted video, do you have a modified script to call that video?

Example... http://www.website.com/video.php

Thank you.

**Comment by grt107** [comment]
@80svault , unfortunately the whole code of this script is written to work only for embed YouTube videos. I may create another jQuery plugin in the future for local videos, but I don't know when it may happen.
